import type { Metadata } from "next";
import "./globals.css";
import { inter, roboto } from "./fonts";
import Navbar from "../components/layouts/header/Navbar";
import { Toaster } from "react-hot-toast";
import Provider from "@/context/Provider";
import dynamic from "next/dynamic";
import Footer from "@/components/layouts/footer/Footer";
const AuthModal = dynamic(() => import("@/components/auth/AuthModal"), {
  ssr: false,
});


export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-inter ${inter.variable}`}>
        <Provider>
          <Navbar />
          <Toaster position="top-center" reverseOrder={false} />
          {children}
          <AuthModal />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
