name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - development
    paths-ignore:
      - "README.md"
      - ".husky"
      - ".github/**"
      - "**/*.csv"
      - .env*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: create env file
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}

        run: |
          touch .env
          echo GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID >> .env
          echo GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET >> .env
          echo MONGODB_URI=$MONGODB_URI >> .env
          echo NEXTAUTH_URL=$NEXTAUTH_URL >> .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "airbnb-clone"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./build/standalone
